///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.Product.Detail
{
    public partial class ui_open_product_detail
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void ClosePopupAdIfExists() 
		{
			// 広告CloseボタンのRxPath
			string closePath =
        		"/dom[@domain='www.automationexercise.com']" +
        		"//iframe//div[#'dismiss-button-element']" +
        		"/div[@innertext='Close']";
			
			IList<Ranorex.Unknown> closeButtons = 
				Host.Local.Find<Ranorex.Unknown>(
					closePath
				);
			
			// 広告が存在しない場合
    		if (closeButtons.Count == 0)
    		{
        		Report.Info(
        		    "ポップアップ広告なし。処理を継続します。"
        		);

        		return;
    		}
    		
    		// 広告を閉じる
    		closeButtons[0].Click();
    		
    		
    		Report.Info(
        		"ポップアップ広告を閉じました。"
    		);
					
		}
        
        public void SaveProductInfo()
    	{
        	
    		string productName =
    			repo.ApplicationUnderTest.ProductsPage.ProductName.InnerText.Trim();

    		string productPrice =
    			repo.ApplicationUnderTest.ProductsPage.ProductPrice.InnerText.Trim();

    		TestContext.ListProductName = productName;
    		TestContext.ListProductPrice = productPrice;

    		Report.Info("商品名を保存しました: " + productName);
    		Report.Info("商品価格を保存しました: " + productPrice);
    		
    	}
    

    }
    
    
}
