///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomationExercise.Product.Detail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ui_validate_product_detail recording.
    /// </summary>
    [TestModule("c80814ff-655f-45d8-a96f-a68f44c45e00", ModuleType.Recording, 1)]
    public partial class ui_validate_product_detail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AutomationExercise.AutomationExerciseRepository repository.
        /// </summary>
        public static global::AutomationExercise.AutomationExerciseRepository repo = global::AutomationExercise.AutomationExerciseRepository.Instance;

        static ui_validate_product_detail instance = new ui_validate_product_detail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ui_validate_product_detail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ui_validate_product_detail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            ScrollAndClickViewProduct();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ApplicationUnderTest.ProductDetailPage.ProductPrice'", repo.ApplicationUnderTest.ProductDetailPage.ProductPriceInfo, new ActionTimeout(10000), new RecordItemIndex(1));
            repo.ApplicationUnderTest.ProductDetailPage.ProductPriceInfo.WaitForExists(10000);
            
            ClosePopupAdIfExists();
            Delay.Milliseconds(0);
            
            ValidateProductDetail();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
