///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.Product.Detail
{
    public partial class ui_validate_product_detail
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        /// <summary>
		/// 商品詳細画面が表示されるまで待機する。
		///
		/// 処理内容:
		/// ・商品詳細領域の表示を確認する。
		/// ・表示されない場合はポップアップ広告を閉じる。
		/// ・広告処理後、再度商品詳細領域を待機する。
		///
		/// Returns:
		/// なし。
		/// </summary>
		public void WaitForProductDetailPage()
		{
			try 
			{
				// 商品詳細領域を最大5秒待機する
				repo.ApplicationUnderTest
					.ProductDetailPage
					.ProductInformationInfo
					.WaitForExists(5000);
				
				Report.Info("商品詳細画面を確認しました。");
				return;
			}	
			catch (Ranorex.ElementNotFoundException)
			{	
				// 初回待機で商品詳細画面を確認できなかった場合
				Report.Warn("商品詳細画面が未表示のため、ポップアップ広告を確認します。");
			}
			
			// ポップアップ広告を確認する
			ClosePopupAdIfExists();
			
			// 広告処理後、商品詳細領域を最大10秒再待機する
			repo.ApplicationUnderTest
				.ProductDetailPage
				.ProductInformationInfo
				.WaitForExists(10000);
			
			
			Report.Info("商品詳細画面を確認しました。");		
			
		}
			
                 
        public void ValidateProductDetail()
		{
    		// 商品詳細画面から各商品情報を取得する
    		string detailProductName =
        		repo.ApplicationUnderTest.ProductDetailPage.ProductName
            		.InnerText.Trim();

    		string detailProductPrice =
        		repo.ApplicationUnderTest.ProductDetailPage.ProductPrice
            		.InnerText.Trim();

    		string category =
        		repo.ApplicationUnderTest.ProductDetailPage.Category
            		.InnerText.Trim();

    		string availability =
        		repo.ApplicationUnderTest.ProductDetailPage.Availability
            		.InnerText.Trim();

    		string condition =
        		repo.ApplicationUnderTest.ProductDetailPage.Condition
            		.InnerText.Trim();

    		string brand =
        		repo.ApplicationUnderTest.ProductDetailPage.Brand
            		.InnerText.Trim();

    		// 商品一覧画面と商品詳細画面の商品名を比較する
    		Validate.AreEqual(
        		detailProductName,
        		TestContext.ListProductName
    		);

    		// 商品一覧画面と商品詳細画面の商品価格を比較する
    		Validate.AreEqual(
        		detailProductPrice,
        		TestContext.ListProductPrice
    		);

    		// 商品詳細情報が表示されていることを確認する
    		Validate.IsTrue(
        		!string.IsNullOrEmpty(category),
        		"カテゴリが表示されていること"
    		);

    		Validate.IsTrue(
        		!string.IsNullOrEmpty(availability),
        		"在庫情報が表示されていること"
    		);

    		Validate.IsTrue(
        		!string.IsNullOrEmpty(condition),
        		"商品状態が表示されていること"
    		);

    		Validate.IsTrue(
        		!string.IsNullOrEmpty(brand),
        		"ブランドが表示されていること"
    		);

    		// 取得した商品詳細情報をレポートへ出力する
    		Report.Info("商品名: " + detailProductName);
    		Report.Info("商品価格: " + detailProductPrice);
    		Report.Info("カテゴリ: " + category);
    		Report.Info("在庫情報: " + availability);
    		Report.Info("商品状態: " + condition);
    		Report.Info("ブランド: " + brand);
		}
        
        public void ClosePopupAdIfExists() 
		{
			// 広告CloseボタンのRxPath
			string closePath =
        		"/dom[@domain='www.automationexercise.com']" +
        		"//iframe//div[#'dismiss-button-element']" +
        		"/div[@innertext='Close']";
			
			IList<Ranorex.Unknown> closeButtons = 
				Host.Local.Find<Ranorex.Unknown>(
					closePath
				);
			
			// 広告が存在しない場合
    		if (closeButtons.Count == 0)
    		{
        		Report.Info(
        		    "ポップアップ広告なし。処理を継続します。"
        		);

        		return;
    		}
    		
    		// 広告を閉じる
    		closeButtons[0].Click();
    		
    		
    		Report.Info(
        		"ポップアップ広告を閉じました。"
    		);
					
		}
        
        
        public void ScrollAndClickViewProduct()
		{
    		// View Product要素を取得する
    		var viewProduct =
        		repo.ApplicationUnderTest.ProductsPage.ViewProduct;

    		// 要素を画面内に表示する
    		viewProduct.EnsureVisible();
    		
    		// 画面下部の広告との重なりを避けるため、
    		// スクロール位置を調整する
    		Mouse.ScrollWheel(-600);

    		// スクロール後の画面描画を待機する
    		Delay.Milliseconds(500);

    		// View Productをクリックする
    		viewProduct.Click();

    		Report.Info("スクロール位置を調整後、View Productをクリックしました。");
		}

    }
}
