//
//機能: Automation Exercise 商品検索APIテスト
//ロジック: searchProduct APIへPOSTし、レスポンスを取得・検証する
//作成者: 馬 猛
//作成日: 2026/08/24
//
///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Script.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.Product.Search
{
	
	
    public partial class Api_searching_product
    {	
		/// <summary>
	/// 商品検索APIレスポンス。
	/// </summary>
		public class ProductSearchResponse
		{
    		public int responseCode { get; set; }

    		public List<Product> products { get; set; }
		}

		/// <summary>
		/// 商品情報。
		/// </summary>
		public class Product
		{
    		public int id { get; set; }

    		public string name { get; set; }

    		public string price { get; set; }

   			public string brand { get; set; }
		}
		    	
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void SearchProductByApi()
        {
            // APIクライアントを生成
            using (HttpClient client = new HttpClient())
            {
                // POSTパラメータを作成
                Dictionary<string, string> parameters =
                    new Dictionary<string, string>()
                    {
                        { "search_product", searchProduct }
                    };

                using (FormUrlEncodedContent content =
                    new FormUrlEncodedContent(parameters))
                {
                    // 商品検索APIを実行
                    HttpResponseMessage response =
                        client.PostAsync(
                            "https://automationexercise.com/api/searchProduct",
                            content
                        ).Result;

                    // レスポンス本文を取得
                    string responseBody =
                        response.Content.ReadAsStringAsync().Result;

                    // ステータスコードをレポート出力
                    Report.Info(
                        "HTTP Status: " +
                        (int)response.StatusCode
                    );

                    // レスポンス本文を出力
                    Report.Info(
                        "API Response: " + responseBody
                    );

                    // HTTP 200を検証
                    Validate.AreEqual(
                        (int)response.StatusCode,
                        200
                    );
                    
                    // JSONをオブジェクトへ変換
                    JavaScriptSerializer serilizer = 
                    	new JavaScriptSerializer();
                    
                    
                    ProductSearchResponse result =
                    	serilizer.Deserialize<ProductSearchResponse>(
                    		responseBody
                    	);
                    // API内部のresponseCodeを検証
            		Validate.AreEqual(
                		result.responseCode,
                		200
            		);

            		// 商品が1件以上存在することを検証
            		Validate.IsTrue(
                		result.products != null &&
                		result.products.Count > 0
            		);

            		// API検索結果をTestContextへ保存
            		TestContext.SearchProduct = searchProduct;
            		TestContext.ApiProductName = result.products[0].name;
            		TestContext.ApiProductCount = result.products.Count;
            		
            		// 全商品名を保存するListを初期化
            		TestContext.ApiProductNames = new List<string>();
            		
            		// APIから取得した全商品名を保存
            		foreach (Product product in result.products)
            		{
            			TestContext.ApiProductNames.Add(
            				product.name
            			);
            		}
            		
            			
            		// API取得結果をログへ出力
            		Report.Info(
                		"検索キーワード: " + TestContext.SearchProduct
            		);

//            		Report.Info(
//                		"API取得商品名: " + TestContext.ApiProductName
//            		);

            		Report.Info(
                		"API取得商品数: " + TestContext.ApiProductCount
            		);
            		
            		// APIの商品名をすべてログへ出力
            		for (int i = 0;
            		     i < TestContext.ApiProductNames.Count;
            		     i++)
            		{
            			Report.Info(
            				"API商品[" +
            				(i + 1) +
            				"]: " +
            				TestContext.ApiProductNames[i]
            			);
            		}
                    
                }
            }
        }

    }
}
