///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.Product.Search
{
    public partial class ui_searching_product
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        /// <summary>
		/// ポップアップ広告が表示された場合に閉じる。
		///
		/// 処理内容:
		/// ・広告iframe内のClose要素を検索する。
		/// ・Closeが存在する場合のみクリックする。
		/// ・広告が存在しない場合はテストを継続する。
		///
		/// Returns:
		/// なし。
		/// </summary>
		public void ClosePopupAdIfExists() 
		{
			// 広告CloseボタンのRxPath
			string closePath =
        		"/dom[@domain='www.automationexercise.com']" +
        		"//iframe//div[#'dismiss-button-element']" +
        		"/div[@innertext='Close']";
			
			IList<Ranorex.Unknown> closeButtons = 
				Host.Local.Find<Ranorex.Unknown>(
					closePath
				);
			
			// 広告が存在しない場合
    		if (closeButtons.Count == 0)
    		{
        		Report.Info(
        		    "ポップアップ広告なし。処理を継続します。"
        		);

        		return;
    		}
    		
    		// 広告を閉じる
    		closeButtons[0].Click();
    		
    		
    		Report.Info(
        		"ポップアップ広告を閉じました。"
    		);
					
		}
        
        
        
        public void ValidateUiProductCount()
		{
    		// Automation ExerciseのDOMを取得
    		WebDocument document =
        		Host.Local.FindSingle<WebDocument>(
            		"/dom[@domain='www.automationexercise.com']",
            		10000
        		);
			
    		int expectedProductCount = TestContext.ApiProductCount;
    		
    		IList<PTag> products = null;
    		
    		// 最多等待10秒，直到UI商品数与API一致
    		for (int i = 0; i < 10; i++)
    		{
    			products = 
    				document.Find<PTag>(
            			".//h2[@innertext='Searched Products']" +
            			"/..//div[@class~'productinfo']/p"
        		);
    			
    			Report.Info(
    				"取得尝试[" + (i + 1) + "]: " +
            		products.Count + "件"
    			);
    			
    			
    			if (products.Count == expectedProductCount)
    			{
    				break;
    			}
    			
    			Delay.Milliseconds(500);
    						
    		}
    		
    		// UIの商品件数を取得
    		int uiPoductCount = products.Count;
    		
       		Report.Info(
        		"API検索結果の商品数: " + expectedProductCount
    		);
    		
    		    		// 取得件数を確認
    		Report.Info(
        		"UI検索結果の商品数: " + uiPoductCount
    		);

    		// 商品名をログ出力
    		for (int i = 0; i < products.Count; i++)
    		{
        		Report.Info(
            		"商品[" +
            		(i + 1) +
            		"]: " +
            		products[i].InnerText
        		);
    		}

    		// 期待件数14件と比較
    		Validate.AreEqual(
        		uiPoductCount,
        		expectedProductCount
    		);
    		
    		// APIの商品名リストが存在することを確認
    		Validate.IsTrue(
    			TestContext.ApiProductNames != null &&
    			TestContext.ApiProductNames.Count > 0
    		);
    		
    		// API商品名リストとUI商品数を比較
    		Validate.AreEqual(
    			TestContext.ApiProductNames.Count,
    			uiPoductCount
    		);
    		
    		
    		// APIとUIの商品名を1件ずつ比較
    		for (int i = 0; i < uiPoductCount; i++)
    		{
    			// UIの商品名を取得
    			string uiProductName = 
    				products[i].InnerText.Trim();
    			
    			// APIの商品名を取得
    			string apiProductName = 
    				TestContext.ApiProductNames[i].Trim();
    			
    			// 比較対象の商品名をログ出力
    			Report.Info(
    				"商品[" + (i + 1) + "] " +
        			"API: " + apiProductName +
        			" / UI: " + uiProductName
    			);
    			
    			// APIとUIの商品名を比較
    			Validate.AreEqual(
    				uiProductName,
    				apiProductName
    			);
    		}
		}
        
        
        
    }
}
