///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomationExercise.Product.Search
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ui_searching_product recording.
    /// </summary>
    [TestModule("80f826fc-aac1-46bb-b1a4-39e06eeb5d60", ModuleType.Recording, 1)]
    public partial class ui_searching_product : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AutomationExercise.AutomationExerciseRepository repository.
        /// </summary>
        public static global::AutomationExercise.AutomationExerciseRepository repo = global::AutomationExercise.AutomationExerciseRepository.Instance;

        static ui_searching_product instance = new ui_searching_product();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ui_searching_product()
        {
            search_content = "top";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ui_searching_product Instance
        {
            get { return instance; }
        }

#region Variables

        string _search_content;

        /// <summary>
        /// Gets or sets the value of variable search_content.
        /// </summary>
        [TestVariable("2814eeac-03b5-4290-b0c6-ff34f0d1d5bf")]
        public string search_content
        {
            get { return _search_content; }
            set { _search_content = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Products_Menu' at Center.", repo.ApplicationUnderTest.Products_MenuInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Products_Menu.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(1));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$search_content' on item 'ApplicationUnderTest.SearchProduct'.", repo.ApplicationUnderTest.SearchProductInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SearchProduct.Element.SetAttributeValue("Value", search_content);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitSearch' at Center.", repo.ApplicationUnderTest.SubmitSearchInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.SubmitSearch.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            ValidateUiProductCount();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
