///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationExerciseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("198c1291-c4f8-440e-975f-c673da20c282")]
    public partial class AutomationExerciseRepository : RepoGenBaseFolder
    {
        static AutomationExerciseRepository instance = new AutomationExerciseRepository();
        AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationExerciseRepository element repository.
        /// </summary>
        [RepositoryFolder("198c1291-c4f8-440e-975f-c673da20c282")]
        public static AutomationExerciseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationExerciseRepository() 
            : base("AutomationExerciseRepository", "/", null, 0, false, "198c1291-c4f8-440e-975f-c673da20c282", ".\\RepositoryImages\\AutomationExerciseRepository198c1291.rximgres")
        {
            _applicationundertest = new AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("198c1291-c4f8-440e-975f-c673da20c282")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
        public virtual AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AutomationExerciseRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            AutomationExerciseRepositoryFolders.ProductsPageFolder _productspage;
            AutomationExerciseRepositoryFolders.ProductDetailPageFolder _productdetailpage;
            RepoItemInfo _products_menuInfo;
            RepoItemInfo _searchproductInfo;
            RepoItemInfo _submitsearchInfo;
            RepoItemInfo _signuploginInfo;
            RepoItemInfo _email_addressInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _login_buttonInfo;
            RepoItemInfo _logout_buttonInfo;
            RepoItemInfo _login_as_testuserInfo;
            RepoItemInfo _brandsInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.automationexercise.com']", parentFolder, 30000, null, false, "40c7c42a-ab65-4243-9e6f-85d8108535bc", "")
            {
                _productspage = new AutomationExerciseRepositoryFolders.ProductsPageFolder(this);
                _productdetailpage = new AutomationExerciseRepositoryFolders.ProductDetailPageFolder(this);
                _products_menuInfo = new RepoItemInfo(this, "Products_Menu", ".//header[#'header']//a[@innertext~'Products']", "", 30000, null, "ece49e18-a297-4a30-bf9e-f0faa070e73a");
                _searchproductInfo = new RepoItemInfo(this, "SearchProduct", ".//input[#'search_product']", "", 30000, null, "fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f");
                _submitsearchInfo = new RepoItemInfo(this, "SubmitSearch", ".//button[#'submit_search']", ".//button[#'submit_search']", 30000, null, "f6a14cf7-d441-4173-8fca-a751a345d1a5");
                _signuploginInfo = new RepoItemInfo(this, "SignupLogin", ".//header[#'header']//a[@innertext~'Signup / Login']", ".//header[#'header']//a[@innertext=' Signup / Login']", 30000, null, "18715491-e9e5-4244-bd9d-08d3796fa309");
                _email_addressInfo = new RepoItemInfo(this, "email_address", ".//div[@class~'login-form']//input[@name='email']", ".//section[#'form']//input[@name='email']", 30000, null, "56f07783-f8a1-4b0e-904a-3bfd55319073");
                _passwordInfo = new RepoItemInfo(this, "password", ".//div[@class~'login-form']//input[@name='password']", ".//section[#'form']//input[@name='password']", 30000, null, "bc78f211-ee4b-410f-88c1-0e0cfadaf899");
                _login_buttonInfo = new RepoItemInfo(this, "login_button", ".//div[@class~'login-form']//button[@innertext='Login']", ".//section[#'form']//button[@innertext='Login']", 30000, null, "fb752a5d-8eab-4a75-9b99-91ba48a8460b");
                _logout_buttonInfo = new RepoItemInfo(this, "logout_button", ".//header[#'header']//a[@innertext~'Logout']", ".//header[#'header']//a[@innertext=' Logout']", 30000, null, "683a1e01-4431-4dae-ab21-b18c832d829a");
                _login_as_testuserInfo = new RepoItemInfo(this, "login_as_testuser", ".//header[#'header']//a[@innertext~'Logged in as']", ".//header[#'header']//a[@innertext=' Logged in as ']", 30000, null, "10390275-c35e-41de-89d4-d2639dbb6908");
                _brandsInfo = new RepoItemInfo(this, "brands", ".//div[@class~'brands_products']//h2[@innertext='Brands']", ".//h2[@innertext='Brands']", 30000, null, "5589a3aa-1e3d-4cae-a647-7012049364d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Products_Menu item.
            /// </summary>
            [RepositoryItem("ece49e18-a297-4a30-bf9e-f0faa070e73a")]
            public virtual Ranorex.ATag Products_Menu
            {
                get
                {
                    return _products_menuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Products_Menu item info.
            /// </summary>
            [RepositoryItemInfo("ece49e18-a297-4a30-bf9e-f0faa070e73a")]
            public virtual RepoItemInfo Products_MenuInfo
            {
                get
                {
                    return _products_menuInfo;
                }
            }

            /// <summary>
            /// The SearchProduct item.
            /// </summary>
            [RepositoryItem("fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f")]
            public virtual Ranorex.InputTag SearchProduct
            {
                get
                {
                    return _searchproductInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchProduct item info.
            /// </summary>
            [RepositoryItemInfo("fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f")]
            public virtual RepoItemInfo SearchProductInfo
            {
                get
                {
                    return _searchproductInfo;
                }
            }

            /// <summary>
            /// The SubmitSearch item.
            /// </summary>
            [RepositoryItem("f6a14cf7-d441-4173-8fca-a751a345d1a5")]
            public virtual Ranorex.ButtonTag SubmitSearch
            {
                get
                {
                    return _submitsearchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitSearch item info.
            /// </summary>
            [RepositoryItemInfo("f6a14cf7-d441-4173-8fca-a751a345d1a5")]
            public virtual RepoItemInfo SubmitSearchInfo
            {
                get
                {
                    return _submitsearchInfo;
                }
            }

            /// <summary>
            /// The SignupLogin item.
            /// </summary>
            [RepositoryItem("18715491-e9e5-4244-bd9d-08d3796fa309")]
            public virtual Ranorex.ATag SignupLogin
            {
                get
                {
                    return _signuploginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignupLogin item info.
            /// </summary>
            [RepositoryItemInfo("18715491-e9e5-4244-bd9d-08d3796fa309")]
            public virtual RepoItemInfo SignupLoginInfo
            {
                get
                {
                    return _signuploginInfo;
                }
            }

            /// <summary>
            /// The email_address item.
            /// </summary>
            [RepositoryItem("56f07783-f8a1-4b0e-904a-3bfd55319073")]
            public virtual Ranorex.InputTag email_address
            {
                get
                {
                    return _email_addressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The email_address item info.
            /// </summary>
            [RepositoryItemInfo("56f07783-f8a1-4b0e-904a-3bfd55319073")]
            public virtual RepoItemInfo email_addressInfo
            {
                get
                {
                    return _email_addressInfo;
                }
            }

            /// <summary>
            /// The password item.
            /// </summary>
            [RepositoryItem("bc78f211-ee4b-410f-88c1-0e0cfadaf899")]
            public virtual Ranorex.InputTag password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The password item info.
            /// </summary>
            [RepositoryItemInfo("bc78f211-ee4b-410f-88c1-0e0cfadaf899")]
            public virtual RepoItemInfo passwordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The login_button item.
            /// </summary>
            [RepositoryItem("fb752a5d-8eab-4a75-9b99-91ba48a8460b")]
            public virtual Ranorex.Button login_button
            {
                get
                {
                    return _login_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The login_button item info.
            /// </summary>
            [RepositoryItemInfo("fb752a5d-8eab-4a75-9b99-91ba48a8460b")]
            public virtual RepoItemInfo login_buttonInfo
            {
                get
                {
                    return _login_buttonInfo;
                }
            }

            /// <summary>
            /// The logout_button item.
            /// </summary>
            [RepositoryItem("683a1e01-4431-4dae-ab21-b18c832d829a")]
            public virtual Ranorex.ATag logout_button
            {
                get
                {
                    return _logout_buttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The logout_button item info.
            /// </summary>
            [RepositoryItemInfo("683a1e01-4431-4dae-ab21-b18c832d829a")]
            public virtual RepoItemInfo logout_buttonInfo
            {
                get
                {
                    return _logout_buttonInfo;
                }
            }

            /// <summary>
            /// The login_as_testuser item.
            /// </summary>
            [RepositoryItem("10390275-c35e-41de-89d4-d2639dbb6908")]
            public virtual Ranorex.ATag login_as_testuser
            {
                get
                {
                    return _login_as_testuserInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The login_as_testuser item info.
            /// </summary>
            [RepositoryItemInfo("10390275-c35e-41de-89d4-d2639dbb6908")]
            public virtual RepoItemInfo login_as_testuserInfo
            {
                get
                {
                    return _login_as_testuserInfo;
                }
            }

            /// <summary>
            /// The brands item.
            /// </summary>
            [RepositoryItem("5589a3aa-1e3d-4cae-a647-7012049364d9")]
            public virtual Ranorex.H2Tag brands
            {
                get
                {
                    return _brandsInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The brands item info.
            /// </summary>
            [RepositoryItemInfo("5589a3aa-1e3d-4cae-a647-7012049364d9")]
            public virtual RepoItemInfo brandsInfo
            {
                get
                {
                    return _brandsInfo;
                }
            }

            /// <summary>
            /// The ProductsPage folder.
            /// </summary>
            [RepositoryFolder("dcaa75a2-fa57-4751-b20f-044b8777ac55")]
            public virtual AutomationExerciseRepositoryFolders.ProductsPageFolder ProductsPage
            {
                get { return _productspage; }
            }

            /// <summary>
            /// The ProductDetailPage folder.
            /// </summary>
            [RepositoryFolder("1c639b65-f904-4938-8237-ac80516f2680")]
            public virtual AutomationExerciseRepositoryFolders.ProductDetailPageFolder ProductDetailPage
            {
                get { return _productdetailpage; }
            }
        }

        /// <summary>
        /// The ProductsPageFolder folder.
        /// </summary>
        [RepositoryFolder("dcaa75a2-fa57-4751-b20f-044b8777ac55")]
        public partial class ProductsPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _viewproductInfo;
            RepoItemInfo _productpriceInfo;
            RepoItemInfo _productnameInfo;

            /// <summary>
            /// Creates a new ProductsPage  folder.
            /// </summary>
            public ProductsPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductsPage", "", parentFolder, 0, null, false, "dcaa75a2-fa57-4751-b20f-044b8777ac55", "")
            {
                _viewproductInfo = new RepoItemInfo(this, "ViewProduct", ".//div[@class='features_items']//div[@class='product-image-wrapper'][1]//div[@class='choose']//a", ".//a[@innertext='View Product']", 30000, null, "6191fab7-7a78-42ed-89c7-9b51d2cba165");
                _productpriceInfo = new RepoItemInfo(this, "ProductPrice", ".//div[@class='features_items']//div[@class='product-image-wrapper'][1]//div[@class~'productinfo']/h2", "element", 30000, null, "85b57e9c-59d4-4f1b-9c59-71f41b53a880");
                _productnameInfo = new RepoItemInfo(this, "ProductName", ".//div[@class='features_items']//div[@class='product-image-wrapper'][1]//div[@class~'productinfo']/p", "element", 30000, null, "5543d3da-21a7-4feb-8d0d-4d2d318ce1de");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dcaa75a2-fa57-4751-b20f-044b8777ac55")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViewProduct item.
            /// </summary>
            [RepositoryItem("6191fab7-7a78-42ed-89c7-9b51d2cba165")]
            public virtual Ranorex.ATag ViewProduct
            {
                get
                {
                    return _viewproductInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ViewProduct item info.
            /// </summary>
            [RepositoryItemInfo("6191fab7-7a78-42ed-89c7-9b51d2cba165")]
            public virtual RepoItemInfo ViewProductInfo
            {
                get
                {
                    return _viewproductInfo;
                }
            }

            /// <summary>
            /// The ProductPrice item.
            /// </summary>
            [RepositoryItem("85b57e9c-59d4-4f1b-9c59-71f41b53a880")]
            public virtual Ranorex.H2Tag ProductPrice
            {
                get
                {
                    return _productpriceInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The ProductPrice item info.
            /// </summary>
            [RepositoryItemInfo("85b57e9c-59d4-4f1b-9c59-71f41b53a880")]
            public virtual RepoItemInfo ProductPriceInfo
            {
                get
                {
                    return _productpriceInfo;
                }
            }

            /// <summary>
            /// The ProductName item.
            /// </summary>
            [RepositoryItem("5543d3da-21a7-4feb-8d0d-4d2d318ce1de")]
            public virtual Ranorex.PTag ProductName
            {
                get
                {
                    return _productnameInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ProductName item info.
            /// </summary>
            [RepositoryItemInfo("5543d3da-21a7-4feb-8d0d-4d2d318ce1de")]
            public virtual RepoItemInfo ProductNameInfo
            {
                get
                {
                    return _productnameInfo;
                }
            }
        }

        /// <summary>
        /// The ProductDetailPageFolder folder.
        /// </summary>
        [RepositoryFolder("1c639b65-f904-4938-8237-ac80516f2680")]
        public partial class ProductDetailPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productnameInfo;
            RepoItemInfo _productpriceInfo;
            RepoItemInfo _categoryInfo;
            RepoItemInfo _availabilityInfo;
            RepoItemInfo _brandInfo;
            RepoItemInfo _conditionInfo;
            RepoItemInfo _productinformationInfo;

            /// <summary>
            /// Creates a new ProductDetailPage  folder.
            /// </summary>
            public ProductDetailPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ProductDetailPage", "", parentFolder, 0, null, false, "1c639b65-f904-4938-8237-ac80516f2680", "")
            {
                _productnameInfo = new RepoItemInfo(this, "ProductName", ".//div[@class~'product-information']/h2", ".//p[@innertext='Category: Women > Tops']", 30000, null, "5efda0cf-083d-42ea-8496-bd172f96b31a");
                _productpriceInfo = new RepoItemInfo(this, "ProductPrice", ".//div[@class~'product-information']//span/span", "element", 30000, null, "7e6f2c93-d243-437f-bde4-89bf3605b817");
                _categoryInfo = new RepoItemInfo(this, "Category", ".//div[@class~'product-information']/p[@innertext~'Category:']", "element", 30000, null, "06defa88-4919-4c43-8e79-5a532190f2cb");
                _availabilityInfo = new RepoItemInfo(this, "Availability", ".//div[@class~'product-information']//b[@innertext='Availability:']", ".//b[@innertext='Availability:']", 30000, null, "5286bf82-e4c4-4588-86ce-b6be5f933440");
                _brandInfo = new RepoItemInfo(this, "Brand", ".//div[@class~'product-information']//b[@innertext='Brand:']", ".//b[@innertext='Brand:']", 30000, null, "52bcbe19-e180-49af-b231-eaa2cbaf6130");
                _conditionInfo = new RepoItemInfo(this, "Condition", ".//div[@class~'product-information']//b[@innertext='Condition:']", ".//b[@innertext='Condition:']", 30000, null, "a558f3a6-36a6-45da-9a7c-7a152634b48b");
                _productinformationInfo = new RepoItemInfo(this, "ProductInformation", ".//div[@class~'product-information']", "element", 30000, null, "5d2b209c-6f76-4293-947c-87923f994f96");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1c639b65-f904-4938-8237-ac80516f2680")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductName item.
            /// </summary>
            [RepositoryItem("5efda0cf-083d-42ea-8496-bd172f96b31a")]
            public virtual Ranorex.H2Tag ProductName
            {
                get
                {
                    return _productnameInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The ProductName item info.
            /// </summary>
            [RepositoryItemInfo("5efda0cf-083d-42ea-8496-bd172f96b31a")]
            public virtual RepoItemInfo ProductNameInfo
            {
                get
                {
                    return _productnameInfo;
                }
            }

            /// <summary>
            /// The ProductPrice item.
            /// </summary>
            [RepositoryItem("7e6f2c93-d243-437f-bde4-89bf3605b817")]
            public virtual Ranorex.SpanTag ProductPrice
            {
                get
                {
                    return _productpriceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ProductPrice item info.
            /// </summary>
            [RepositoryItemInfo("7e6f2c93-d243-437f-bde4-89bf3605b817")]
            public virtual RepoItemInfo ProductPriceInfo
            {
                get
                {
                    return _productpriceInfo;
                }
            }

            /// <summary>
            /// The Category item.
            /// </summary>
            [RepositoryItem("06defa88-4919-4c43-8e79-5a532190f2cb")]
            public virtual Ranorex.PTag Category
            {
                get
                {
                    return _categoryInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Category item info.
            /// </summary>
            [RepositoryItemInfo("06defa88-4919-4c43-8e79-5a532190f2cb")]
            public virtual RepoItemInfo CategoryInfo
            {
                get
                {
                    return _categoryInfo;
                }
            }

            /// <summary>
            /// The Availability item.
            /// </summary>
            [RepositoryItem("5286bf82-e4c4-4588-86ce-b6be5f933440")]
            public virtual Ranorex.BTag Availability
            {
                get
                {
                    return _availabilityInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The Availability item info.
            /// </summary>
            [RepositoryItemInfo("5286bf82-e4c4-4588-86ce-b6be5f933440")]
            public virtual RepoItemInfo AvailabilityInfo
            {
                get
                {
                    return _availabilityInfo;
                }
            }

            /// <summary>
            /// The Brand item.
            /// </summary>
            [RepositoryItem("52bcbe19-e180-49af-b231-eaa2cbaf6130")]
            public virtual Ranorex.BTag Brand
            {
                get
                {
                    return _brandInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The Brand item info.
            /// </summary>
            [RepositoryItemInfo("52bcbe19-e180-49af-b231-eaa2cbaf6130")]
            public virtual RepoItemInfo BrandInfo
            {
                get
                {
                    return _brandInfo;
                }
            }

            /// <summary>
            /// The Condition item.
            /// </summary>
            [RepositoryItem("a558f3a6-36a6-45da-9a7c-7a152634b48b")]
            public virtual Ranorex.BTag Condition
            {
                get
                {
                    return _conditionInfo.CreateAdapter<Ranorex.BTag>(true);
                }
            }

            /// <summary>
            /// The Condition item info.
            /// </summary>
            [RepositoryItemInfo("a558f3a6-36a6-45da-9a7c-7a152634b48b")]
            public virtual RepoItemInfo ConditionInfo
            {
                get
                {
                    return _conditionInfo;
                }
            }

            /// <summary>
            /// The ProductInformation item.
            /// </summary>
            [RepositoryItem("5d2b209c-6f76-4293-947c-87923f994f96")]
            public virtual Ranorex.DivTag ProductInformation
            {
                get
                {
                    return _productinformationInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductInformation item info.
            /// </summary>
            [RepositoryItemInfo("5d2b209c-6f76-4293-947c-87923f994f96")]
            public virtual RepoItemInfo ProductInformationInfo
            {
                get
                {
                    return _productinformationInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
