///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationExerciseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("198c1291-c4f8-440e-975f-c673da20c282")]
    public partial class AutomationExerciseRepository : RepoGenBaseFolder
    {
        static AutomationExerciseRepository instance = new AutomationExerciseRepository();
        AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationExerciseRepository element repository.
        /// </summary>
        [RepositoryFolder("198c1291-c4f8-440e-975f-c673da20c282")]
        public static AutomationExerciseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationExerciseRepository() 
            : base("AutomationExerciseRepository", "/", null, 0, false, "198c1291-c4f8-440e-975f-c673da20c282", ".\\RepositoryImages\\AutomationExerciseRepository198c1291.rximgres")
        {
            _applicationundertest = new AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("198c1291-c4f8-440e-975f-c673da20c282")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
        public virtual AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AutomationExerciseRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _products_menuInfo;
            RepoItemInfo _searchproductInfo;
            RepoItemInfo _submitsearchInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.automationexercise.com']", parentFolder, 30000, null, false, "40c7c42a-ab65-4243-9e6f-85d8108535bc", "")
            {
                _products_menuInfo = new RepoItemInfo(this, "Products_Menu", ".//header[#'header']/div/div/div/div[2]/?/?/ul/li[2]/a[@innertext=' Products']", "", 30000, null, "ece49e18-a297-4a30-bf9e-f0faa070e73a");
                _searchproductInfo = new RepoItemInfo(this, "SearchProduct", ".//input[#'search_product']", "", 30000, null, "fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f");
                _submitsearchInfo = new RepoItemInfo(this, "SubmitSearch", ".//button[#'submit_search']", ".//button[#'submit_search']", 30000, null, "f6a14cf7-d441-4173-8fca-a751a345d1a5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Products_Menu item.
            /// </summary>
            [RepositoryItem("ece49e18-a297-4a30-bf9e-f0faa070e73a")]
            public virtual Ranorex.ATag Products_Menu
            {
                get
                {
                    return _products_menuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Products_Menu item info.
            /// </summary>
            [RepositoryItemInfo("ece49e18-a297-4a30-bf9e-f0faa070e73a")]
            public virtual RepoItemInfo Products_MenuInfo
            {
                get
                {
                    return _products_menuInfo;
                }
            }

            /// <summary>
            /// The SearchProduct item.
            /// </summary>
            [RepositoryItem("fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f")]
            public virtual Ranorex.InputTag SearchProduct
            {
                get
                {
                    return _searchproductInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchProduct item info.
            /// </summary>
            [RepositoryItemInfo("fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f")]
            public virtual RepoItemInfo SearchProductInfo
            {
                get
                {
                    return _searchproductInfo;
                }
            }

            /// <summary>
            /// The SubmitSearch item.
            /// </summary>
            [RepositoryItem("f6a14cf7-d441-4173-8fca-a751a345d1a5")]
            public virtual Ranorex.ButtonTag SubmitSearch
            {
                get
                {
                    return _submitsearchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitSearch item info.
            /// </summary>
            [RepositoryItemInfo("f6a14cf7-d441-4173-8fca-a751a345d1a5")]
            public virtual RepoItemInfo SubmitSearchInfo
            {
                get
                {
                    return _submitsearchInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
