///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationExerciseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("198c1291-c4f8-440e-975f-c673da20c282")]
    public partial class AutomationExerciseRepository : RepoGenBaseFolder
    {
        static AutomationExerciseRepository instance = new AutomationExerciseRepository();
        AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationExerciseRepository element repository.
        /// </summary>
        [RepositoryFolder("198c1291-c4f8-440e-975f-c673da20c282")]
        public static AutomationExerciseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationExerciseRepository() 
            : base("AutomationExerciseRepository", "/", null, 0, false, "198c1291-c4f8-440e-975f-c673da20c282", ".\\RepositoryImages\\AutomationExerciseRepository198c1291.rximgres")
        {
            _applicationundertest = new AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("198c1291-c4f8-440e-975f-c673da20c282")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
        public virtual AutomationExerciseRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AutomationExerciseRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _products_menuInfo;
            RepoItemInfo _searchproductInfo;
            RepoItemInfo _submitsearchInfo;
            RepoItemInfo _signuploginInfo;
            RepoItemInfo _email_addressInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _login_buttonInfo;
            RepoItemInfo _logout_buttonInfo;
            RepoItemInfo _login_as_testuserInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.automationexercise.com']", parentFolder, 30000, null, false, "40c7c42a-ab65-4243-9e6f-85d8108535bc", "")
            {
                _products_menuInfo = new RepoItemInfo(this, "Products_Menu", ".//header[#'header']/div/div/div/div[2]/?/?/ul/li[2]/a[@innertext=' Products']", "", 30000, null, "ece49e18-a297-4a30-bf9e-f0faa070e73a");
                _searchproductInfo = new RepoItemInfo(this, "SearchProduct", ".//input[#'search_product']", "", 30000, null, "fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f");
                _submitsearchInfo = new RepoItemInfo(this, "SubmitSearch", ".//button[#'submit_search']", ".//button[#'submit_search']", 30000, null, "f6a14cf7-d441-4173-8fca-a751a345d1a5");
                _signuploginInfo = new RepoItemInfo(this, "SignupLogin", ".//header[#'header']/div/div/div/div[2]/?/?/ul/li[4]/a[@innertext=' Signup / Login']", ".//header[#'header']//a[@innertext=' Signup / Login']", 30000, null, "18715491-e9e5-4244-bd9d-08d3796fa309");
                _email_addressInfo = new RepoItemInfo(this, "email_address", ".//section[#'form']/div/div/div[1]/?/?/form[@action='https://www.automationexercise.com/login']/input[@name='email']", ".//section[#'form']//input[@name='email']", 30000, null, "56f07783-f8a1-4b0e-904a-3bfd55319073");
                _passwordInfo = new RepoItemInfo(this, "password", ".//section[#'form']/div/div/div[1]/?/?/form[@action='https://www.automationexercise.com/login']/input[@name='password']", ".//section[#'form']//input[@name='password']", 30000, null, "bc78f211-ee4b-410f-88c1-0e0cfadaf899");
                _login_buttonInfo = new RepoItemInfo(this, "login_button", ".//section[#'form']/div/div/div[1]/?/?/form[@action='https://www.automationexercise.com/login']/button[@innertext='Login']", ".//section[#'form']//button[@innertext='Login']", 30000, null, "fb752a5d-8eab-4a75-9b99-91ba48a8460b");
                _logout_buttonInfo = new RepoItemInfo(this, "logout_button", ".//header[#'header']/div/div/div/div[2]/?/?/ul/li[4]/a[@innertext=' Logout']", ".//header[#'header']//a[@innertext=' Logout']", 30000, null, "683a1e01-4431-4dae-ab21-b18c832d829a");
                _login_as_testuserInfo = new RepoItemInfo(this, "login_as_testuser", ".//header[#'header']/div/div/div/div[2]/?/?/ul/li[10]/a[@innertext=' Logged in as ']", ".//header[#'header']//a[@innertext=' Logged in as ']", 30000, null, "10390275-c35e-41de-89d4-d2639dbb6908");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("40c7c42a-ab65-4243-9e6f-85d8108535bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Products_Menu item.
            /// </summary>
            [RepositoryItem("ece49e18-a297-4a30-bf9e-f0faa070e73a")]
            public virtual Ranorex.ATag Products_Menu
            {
                get
                {
                    return _products_menuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Products_Menu item info.
            /// </summary>
            [RepositoryItemInfo("ece49e18-a297-4a30-bf9e-f0faa070e73a")]
            public virtual RepoItemInfo Products_MenuInfo
            {
                get
                {
                    return _products_menuInfo;
                }
            }

            /// <summary>
            /// The SearchProduct item.
            /// </summary>
            [RepositoryItem("fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f")]
            public virtual Ranorex.InputTag SearchProduct
            {
                get
                {
                    return _searchproductInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchProduct item info.
            /// </summary>
            [RepositoryItemInfo("fd0b7cc1-fc3f-4beb-aa4b-e221a80d531f")]
            public virtual RepoItemInfo SearchProductInfo
            {
                get
                {
                    return _searchproductInfo;
                }
            }

            /// <summary>
            /// The SubmitSearch item.
            /// </summary>
            [RepositoryItem("f6a14cf7-d441-4173-8fca-a751a345d1a5")]
            public virtual Ranorex.ButtonTag SubmitSearch
            {
                get
                {
                    return _submitsearchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SubmitSearch item info.
            /// </summary>
            [RepositoryItemInfo("f6a14cf7-d441-4173-8fca-a751a345d1a5")]
            public virtual RepoItemInfo SubmitSearchInfo
            {
                get
                {
                    return _submitsearchInfo;
                }
            }

            /// <summary>
            /// The SignupLogin item.
            /// </summary>
            [RepositoryItem("18715491-e9e5-4244-bd9d-08d3796fa309")]
            public virtual Ranorex.ATag SignupLogin
            {
                get
                {
                    return _signuploginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignupLogin item info.
            /// </summary>
            [RepositoryItemInfo("18715491-e9e5-4244-bd9d-08d3796fa309")]
            public virtual RepoItemInfo SignupLoginInfo
            {
                get
                {
                    return _signuploginInfo;
                }
            }

            /// <summary>
            /// The email_address item.
            /// </summary>
            [RepositoryItem("56f07783-f8a1-4b0e-904a-3bfd55319073")]
            public virtual Ranorex.InputTag email_address
            {
                get
                {
                    return _email_addressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The email_address item info.
            /// </summary>
            [RepositoryItemInfo("56f07783-f8a1-4b0e-904a-3bfd55319073")]
            public virtual RepoItemInfo email_addressInfo
            {
                get
                {
                    return _email_addressInfo;
                }
            }

            /// <summary>
            /// The password item.
            /// </summary>
            [RepositoryItem("bc78f211-ee4b-410f-88c1-0e0cfadaf899")]
            public virtual Ranorex.InputTag password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The password item info.
            /// </summary>
            [RepositoryItemInfo("bc78f211-ee4b-410f-88c1-0e0cfadaf899")]
            public virtual RepoItemInfo passwordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The login_button item.
            /// </summary>
            [RepositoryItem("fb752a5d-8eab-4a75-9b99-91ba48a8460b")]
            public virtual Ranorex.Button login_button
            {
                get
                {
                    return _login_buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The login_button item info.
            /// </summary>
            [RepositoryItemInfo("fb752a5d-8eab-4a75-9b99-91ba48a8460b")]
            public virtual RepoItemInfo login_buttonInfo
            {
                get
                {
                    return _login_buttonInfo;
                }
            }

            /// <summary>
            /// The logout_button item.
            /// </summary>
            [RepositoryItem("683a1e01-4431-4dae-ab21-b18c832d829a")]
            public virtual Ranorex.ATag logout_button
            {
                get
                {
                    return _logout_buttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The logout_button item info.
            /// </summary>
            [RepositoryItemInfo("683a1e01-4431-4dae-ab21-b18c832d829a")]
            public virtual RepoItemInfo logout_buttonInfo
            {
                get
                {
                    return _logout_buttonInfo;
                }
            }

            /// <summary>
            /// The login_as_testuser item.
            /// </summary>
            [RepositoryItem("10390275-c35e-41de-89d4-d2639dbb6908")]
            public virtual Ranorex.ATag login_as_testuser
            {
                get
                {
                    return _login_as_testuserInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The login_as_testuser item info.
            /// </summary>
            [RepositoryItemInfo("10390275-c35e-41de-89d4-d2639dbb6908")]
            public virtual RepoItemInfo login_as_testuserInfo
            {
                get
                {
                    return _login_as_testuserInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
