///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.Brand
{
    public partial class ui_brand_list
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        /// <summary>
		/// ポップアップ広告が表示された場合に閉じる。
		///
		/// 処理内容:
		/// ・広告iframe内のClose要素を検索する。
		/// ・Closeが存在する場合のみクリックする。
		/// ・広告が存在しない場合はテストを継続する。
		///
		/// Returns:
		/// なし。
		/// </summary>
		public void ClosePopupAdIfExists() 
		{
			// 広告CloseボタンのRxPath
			string closePath =
        		"/dom[@domain='www.automationexercise.com']" +
        		"//iframe//div[#'dismiss-button-element']" +
        		"/div[@innertext='Close']";
			
			IList<Ranorex.Unknown> closeButtons = 
				Host.Local.Find<Ranorex.Unknown>(
					closePath
				);
			
			// 広告が存在しない場合
    		if (closeButtons.Count == 0)
    		{
        		Report.Info(
        		    "ポップアップ広告なし。処理を継続します。"
        		);

        		return;
    		}
    		
    		// 広告を閉じる
    		closeButtons[0].Click();
    		
    		
    		Report.Info(
        		"ポップアップ広告を閉じました。"
    		);
					
		}
		
		
		/// <summary>
		/// APIとUIのブランド一覧を比較する。
		///
		/// 処理内容:
		/// ・UI上のブランド一覧を取得する。
		/// ・APIブランド一覧から重複を除外する。
		/// ・APIとUIのブランド件数を比較する。
		/// ・APIとUIのブランド名を比較する。
		///
		/// Returns:
		/// なし。
		/// </summary>
		public void ValidateBrandList()
		{
			// Automation ExerciseのDOMを取得
			WebDocument document =
				Host.Local.FindSingle<WebDocument>(
					"/dom[@domain='www.automationexercise.com']",
					15000
				);
		
			// UIブランド一覧のRxPath
			string brandPath =
				".//div[@class='brands_products']//ul/li";
		
			// UIブランド要素を取得
			IList<LiTag> brandItems =
				document.Find<LiTag>(
					brandPath
				);
		
			Report.Info(
				"UIブランド取得件数: " +
				brandItems.Count
			);
		
			// UIブランド名を格納
			List<string> uiBrandNames =
				new List<string>();
		
			foreach (LiTag brandItem in brandItems)
			{	
				// li配下のaタグを取得
				ATag brandLink =
        			brandItem.FindSingle<ATag>(
            			".//a",
            			5000
        			);
				
				// aタグから表示文字列を取得
    			string brandText =
        			brandLink.InnerText.Trim();
    			
    			
    			Report.Info(
        			"UIブランド原文: " +
        			brandText
    			);
				
				// UI上の件数表示などを除去する
				// 例: "(6) Polo" → "Polo"
				string brandName =
					Regex.Replace(
						brandText,
						@"^\s*\(\d+\)\s*",
						""
					).Trim();
		
				uiBrandNames.Add(
					brandName
				);
		
				Report.Info(
					"UIブランド: " +
					brandName
				);
			}
		
			// APIブランド名を重複除去
			List<string> apiUniqueBrandNames =
				new List<string>();
		
			foreach (string brandName
				in TestContext.ApiBrandNames)
			{
				if (!apiUniqueBrandNames.Contains(
					brandName))
				{
					apiUniqueBrandNames.Add(
						brandName
					);
				}
			}
		
			Report.Info(
				"APIユニークブランド数: " +
				apiUniqueBrandNames.Count
			);
		
			Report.Info(
				"UIブランド数: " +
				uiBrandNames.Count
			);
		
			// ブランド件数を比較
			Validate.AreEqual(
				uiBrandNames.Count,
				apiUniqueBrandNames.Count
			);
		
			// APIブランド名がUIに存在することを確認
			foreach (string apiBrandName
				in apiUniqueBrandNames)
			{
				Report.Info(
					"ブランド確認: " +
					apiBrandName
				);
		
				Validate.IsTrue(
					uiBrandNames.Contains(
						apiBrandName
					)
				);
			}
		}
		
		
		

    }
}
