///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomationExercise.Brand
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ui_brand_list recording.
    /// </summary>
    [TestModule("66fc7681-3e4b-4413-95a1-27f02c5796a9", ModuleType.Recording, 1)]
    public partial class ui_brand_list : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AutomationExercise.AutomationExerciseRepository repository.
        /// </summary>
        public static global::AutomationExercise.AutomationExerciseRepository repo = global::AutomationExercise.AutomationExerciseRepository.Instance;

        static ui_brand_list instance = new ui_brand_list();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ui_brand_list()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ui_brand_list Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Products_Menu' at Center.", repo.ApplicationUnderTest.Products_MenuInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Products_Menu.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            ClosePopupAdIfExists();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.brands'", repo.ApplicationUnderTest.brandsInfo, new ActionTimeout(5000), new RecordItemIndex(3));
            repo.ApplicationUnderTest.brandsInfo.WaitForExists(5000);
            
            ValidateBrandList();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
