///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Script.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.Product.List
{
    public partial class api_product_list
    {
    	/// <summary>
		/// 商品検索APIレスポンス。
		/// </summary>
		public class ProductSearchResponse
		{
    		public int responseCode { get; set; }

    		public List<Product> products { get; set; }
		}

		/// <summary>
		/// 商品情報。
		/// </summary>
		public class Product
		{
    		public int id { get; set; }

    		public string name { get; set; }

    		public string price { get; set; }

   			public string brand { get; set; }
		}

    	
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void GetProductListByApi()
        {
        	// APIクライアントを生成
        	using (HttpClient client = new HttpClient())
        	{
        		// 商品一覧APIを実行
        		HttpResponseMessage response =
            		client.GetAsync(
                		"https://automationexercise.com/api/productsList"
            		).Result;

        		// レスポンス本文を取得
        		string responseBody =
            		response.Content.ReadAsStringAsync().Result;
        		
        		//HTTPステータスを取得
        		int statusCode = 
        			(int)response.StatusCode;
        		
        		Report.Info(
        			"HTTP Status: " + statusCode
        		);
        		
        		// HTTP 200を検証
        		Validate.AreEqual(
        			statusCode,
        			200
        		);
        		
        		// JSONをオブジェクトへ変換
        		JavaScriptSerializer serializer = 
        			new JavaScriptSerializer();
        		
        		ProductSearchResponse result =
        			serializer.Deserialize<ProductSearchResponse>(
        				responseBody
        			);
        		
        		// API内部のresponseCodeを検証
        		Validate.AreEqual(
        			result.responseCode,
        			200
        		);
        		
        		// 商品一覧が存在することを検証
        		Validate.IsTrue(
        			result.products != null &&
        			result.products.Count > 0
        		);
        		
        		
        		// 商品総数を共有データへ保存
        		TestContext.ApiProductCount = 
        			result.products.Count;
        		
        		// API商品総数をログ出力
        		Report.Info(
            		"API商品総数: " +
            		TestContext.ApiProductCount
        		);
        		
        	}
        }
    }
}
