///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.Product.List
{
    public partial class ui_product_list
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        
        public void ClosePopupAdIfExists() 
		{
			// 広告CloseボタンのRxPath
			string closePath =
        		"/dom[@domain='www.automationexercise.com']" +
        		"//iframe//div[#'dismiss-button-element']" +
        		"/div[@innertext='Close']";
			
			IList<Ranorex.Unknown> closeButtons = 
				Host.Local.Find<Ranorex.Unknown>(
					closePath
				);
			
			// 広告が存在しない場合
    		if (closeButtons.Count == 0)
    		{
        		Report.Info(
        		    "ポップアップ広告なし。処理を継続します。"
        		);

        		return;
    		}
    		
    		// 広告を閉じる
    		closeButtons[0].Click();
    		
    		
    		Report.Info(
        		"ポップアップ広告を閉じました。"
    		);
					
		}
        
        public void ValidateUiProductListCount()
		{
    		// Automation ExerciseのDOMを取得
    		WebDocument document =
        		Host.Local.FindSingle<WebDocument>(
            		"/dom[@domain='www.automationexercise.com']",
            		10000
        		);

    		// APIの商品総数を取得
    		int expectedProductCount =
        		TestContext.ApiProductCount;

    		// UIの商品一覧を取得
    		IList<PTag> products =
        		document.Find<PTag>(
            		".//div[@class~'features_items']" +
            		"//div[@class~'productinfo']/p"
        		);

    		// UIの商品総数を取得
    		int uiProductCount = products.Count;

    		// APIの商品総数をログ出力
    		Report.Info(
        		"API商品総数: " +
        		expectedProductCount
    		);

    		// UIの商品総数をログ出力
    		Report.Info(
        		"UI商品総数: " +
        		uiProductCount
    		);

    		// APIとUIの商品総数を比較
    		Validate.AreEqual(
        		uiProductCount,
        		expectedProductCount
    		);
		}
        

    }
}
