///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationExercise.User
{
    public partial class ui_login
    {
        /// <summary>
        /// Recording開始時の初期化処理。
        ///
        /// 処理内容:
        /// ・APIで作成したメールアドレスを取得する。
        /// ・APIで作成したパスワードを取得する。
        /// ・Recording変数へ設定する。
        ///
        /// Returns:
        /// なし。
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
            // APIで作成したユーザー情報を取得
            email = global:: AutomationExercise.TestContext.UserEmail;
            
            password = global:: AutomationExercise.TestContext.UserPassword;
            
            // ログ出力
            Report.Info("ログインメールアドレス: " + email);
            
            Report.Info("ログインパスワードをTestContextから取得しました。");
        }

    }
}
