///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomationExercise.User
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ui_login recording.
    /// </summary>
    [TestModule("9e7f8747-4f9e-46ce-8ebb-32ecbebc41b6", ModuleType.Recording, 1)]
    public partial class ui_login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AutomationExercise.AutomationExerciseRepository repository.
        /// </summary>
        public static global::AutomationExercise.AutomationExerciseRepository repo = global::AutomationExercise.AutomationExerciseRepository.Instance;

        static ui_login instance = new ui_login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ui_login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ui_login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SignupLogin' at 37;14.", repo.ApplicationUnderTest.SignupLoginInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SignupLogin.Click("37;14");
            Delay.Milliseconds(0);
            
            WaitForLoginPage();
            Delay.Milliseconds(0);
            
            SetLoginCredentials();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.login_button' at Center.", repo.ApplicationUnderTest.login_buttonInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.login_button.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.logout_button'.", repo.ApplicationUnderTest.logout_buttonInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ApplicationUnderTest.logout_buttonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>' Logged in as ') on item 'ApplicationUnderTest.login_as_testuser'.", repo.ApplicationUnderTest.login_as_testuserInfo, new RecordItemIndex(5));
            Validate.AttributeContains(repo.ApplicationUnderTest.login_as_testuserInfo, "Text", " Logged in as ");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
