name: Ranorex CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ranorex-test:
    runs-on:
      - self-hosted
      - windows
      - x64

    steps:
        # GitHub repository コード取得
      - name: Checkout repository
        uses: actions/checkout@v4
        
        # MSBuild环境セットアップ       
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
        # Ranorex Solution　ビルド
      - name: Build Ranorex solution
        run: msbuild AutomationExercise.sln /p:Configuration=Debug
        
      - name: Check build output
        shell: powershell
        run: |
          Write-Host "=== Ranorex Build Output ==="
          Get-ChildItem ".\AutomationExercise\bin\Debug" -Recurse
               
        # Ranorex Test Suite実行
      - name: Run Ranorex Test Suite
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "TestResults"

          .\AutomationExercise\bin\Debug\AutomationExercise.exe `
            /reportfile:"TestResults\AutomationExercise.rxlog"
        
      
      - name: Upload Ranorex Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ranorex-reports
          path: TestResults/
          if-no-files-found: warn